export interface BoliviaDepartment {
  name: string;
  provinces: string[];
}

export const BOLIVIA_DEPARTMENTS: BoliviaDepartment[] = [
  { name: 'BENI', provinces: ['CERCADO', 'ANTONIO VACA DÍEZ', 'GENERAL JOSÉ BALLIVIÁN', 'YACUMA', 'MOXOS', 'MARBÁN', 'MAMORÉ', 'ITÉNEZ'] },
  { name: 'CHUQUISACA', provinces: ['OROPEZA', 'AZURDUY', 'ZUDÁÑEZ', 'TOMINA', 'HERNANDO SILES', 'YAMPARÁEZ', 'NOR CINTI', 'SUD CINTI', 'BELISARIO BOETO', 'LUIS CALVO'] },
  { name: 'COCHABAMBA', provinces: ['CERCADO', 'CAMPERO', 'AYOPAYA', 'ESTEBAN ARCE', 'ARANI', 'ARQUE', 'CAPINOTA', 'GERMÁN JORDÁN', 'QUILLACOLLO', 'CHAPARE', 'TAPACARÍ', 'CARRASCO', 'MIZQUE', 'PUNATA', 'BOLÍVAR', 'TIRAQUE'] },
  { name: 'LA PAZ', provinces: ['MURILLO', 'OMASUYOS', 'PACAJES', 'CAMACHO', 'MUÑECAS', 'LARECAJA', 'FRANZ TAMAYO', 'INGAVI', 'LOAYZA', 'INQUISIVI', 'SUD YUNGAS', 'LOS ANDES', 'AROMA', 'NOR YUNGAS', 'ABEL ITURRALDE', 'BAUTISTA SAAVEDRA', 'MANCO KAPAC', 'GUALBERTO VILLARROEL', 'GENERAL JOSÉ MANUEL PANDO', 'CARANAVI'] },
  { name: 'ORURO', provinces: ['CERCADO', 'EDUARDO AVAROA', 'CARANGAS', 'SAJAMA', 'LITORAL', 'POOPÓ', 'PANTALEÓN DALENCE', 'LADISLAO CABRERA', 'SABAYA', 'SAUCARÍ', 'TOMÁS BARRÓN', 'SUR CARANGAS', 'SEBASTIÁN PAGADOR', 'MEJILLONES', 'NOR CARANGAS', 'SAN PEDRO DE TOTORA'] },
  { name: 'PANDO', provinces: ['NICOLÁS SUÁREZ', 'MANURIPI', 'MADRE DE DIOS', 'ABUNÁ', 'FEDERICO ROMÁN'] },
  { name: 'POTOSÍ', provinces: ['TOMÁS FRÍAS', 'RAFAEL BUSTILLO', 'CORNELIO SAAVEDRA', 'CHAYANTA', 'CHARCAS', 'NOR CHICHAS', 'ALONSO DE IBÁÑEZ', 'SUD CHICHAS', 'NOR LÍPEZ', 'SUD LÍPEZ', 'JOSÉ MARÍA LINARES', 'ANTONIO QUIJARRO', 'GENERAL BERNARDINO BILBAO', 'DANIEL CAMPOS', 'MODESTO OMISTE', 'ENRIQUE BALDIVIESO'] },
  { name: 'SANTA CRUZ', provinces: ['ANDRÉS IBÁÑEZ', 'WARNES', 'VELASCO', 'ICHILO', 'CHIQUITOS', 'SARA', 'CORDILLERA', 'VALLEGRANDE', 'FLORIDA', 'OBISPO SANTISTEVAN', 'ÑUFLO DE CHÁVEZ', 'ÁNGEL SANDÓVAL', 'MANUEL MARÍA CABALLERO', 'GERMÁN BUSCH', 'GUARAYOS'] },
  { name: 'TARIJA', provinces: ['CERCADO', 'ANICETO ARCE', 'GRAN CHACO', 'JOSÉ MARÍA AVILÉS', 'EUSTAQUIO MÉNDEZ', 'BURDET O’CONNOR'] },
];
