import { NAVIGATION_DESTINATIONS as R, NavigationDestination } from 'src/app/core/constants/application-navigation.constants';
import { MenuItem } from './menu.model';
const l=(id:number,label:string,r:NavigationDestination):MenuItem=>({id,label,icon:'fa-solid fa-angle-right',link:r.path,name:r.permission?.name,action:r.permission?.action});
const g=(id:number,label:string,icon:string,subItems:MenuItem[]):MenuItem=>({id,label,icon,subItems}); const t=(id:number,label:string):MenuItem=>({id,label,isTitle:true});
export const MENU: MenuItem[]=[
t(1,'Dashboard'),{...l(2,'Dashboard',R.dashboard),icon:'fa-solid fa-chart-simple'},
t(10,'Comercial'),{...l(12,'Gestión de proveedores',R.providers),icon:'fa-solid fa-users'},l(16,'Compras de proveedor',R.providerPurchases),l(15,'Cuentas de proveedor',R.providerAccounts),l(13,'Agendar recojos',R.providerPickup),l(14,'Certificaciones',R.providerCertification),l(17,'Reporte comercial',R.commercialReport),
t(20,'Entradas'),{...l(21,'Proveedores',R.providers),icon:'fa-solid fa-users'},{...l(22,'Clientes',R.clients),icon:'fa-solid fa-user-group'},g(23,'Compras','fa-solid fa-truck',[l(134,'Realizar compras',R.createPurchase),l(24,'Gestión de compras',R.queryPurchases),l(25,'Lista de proveedores',R.providers),l(26,'Reporte de compras',R.purchaseReport)]),g(27,'Clasificados','fa-solid fa-boxes-packing',[l(135,'Realizar clasificados',R.createClassified),l(28,'Gestión de clasificados',R.queryClassifieds)]),{...l(29,'Recepciones',R.queryReceptions),icon:'fa-solid fa-box-open'},{...l(30,'Conciliaciones',R.reconciliations),icon:'fa-solid fa-scale-balanced'},
t(40,'Balanza'),{...l(41,'Balanza camionera',R.truckScaleQuery),icon:'fa-solid fa-truck-fast'},{...l(42,'Balanza manual',R.manualScaleQuery),icon:'fa-solid fa-weight-scale'},{...l(43,'Servicio de balanza',R.scaleServiceQuery),icon:'fa-solid fa-calculator'},{...l(44,'Transportistas',R.driverQuery),icon:'fa-solid fa-user-tie'},{...l(45,'Camiones',R.truckQuery),icon:'fa-solid fa-truck-pickup'},
t(50,'Salidas'),g(51,'Ventas','fa-solid fa-cart-plus',[l(52,'Clientes',R.clients),l(53,'Gestión de ventas',R.querySales),l(54,'Reporte de ventas',R.salesReport)]),{...l(55,'Clientes',R.clients),icon:'fa-solid fa-user-group'},g(56,'Traslados','fa-solid fa-truck-ramp-box',[l(136,'Realizar traslado',R.createTransfer),l(57,'Gestión de traslados',R.queryTransfers)]),{...l(60,'Despachos',R.dispatches),icon:'fa-solid fa-dolly'},
t(70,'Administración de caja'),g(71,'Caja','fa-solid fa-vault',[l(72,'Dashboard de caja',R.cashDashboard),l(73,'Consultar caja',R.cashQuery),l(74,'Gestión de gastos',R.cashExpenses),l(75,'Transferencias (mayor)',R.cashMajorTransfers),l(76,'Reporte de finanzas',R.financeReport)]),g(77,'Ingreso de activos','fa-solid fa-money-bill-transfer',[l(78,'Solicitud de compra',R.assetPurchaseRequest),l(79,'Orden de compra',R.assetPurchaseOrder),l(80,'Gestión de compra',R.assetPurchaseManagement)]),g(81,'Salida de activos','fa-solid fa-arrow-right-from-bracket',[l(82,'Insumos consumibles',R.assetConsumables),l(83,'Herramientas',R.assetTools),l(84,'Gestión de salidas',R.assetOutputManagement)]),g(85,'Cuentas','fa-solid fa-comments-dollar',[l(86,'Cuentas por pagar',R.accountsPayable),l(87,'Cuentas por cobrar',R.accountsReceivable)]),
t(90,'Inventario'),g(91,'Inventario activo fijo','fa-solid fa-boxes-stacked',[l(92,'Insumos y consumibles',R.fixedAssetSupplies),l(93,'Maquinaria',R.fixedAssetMachinery),l(94,'Vehículos',R.fixedAssetVehicles),l(95,'Muebles y oficina',R.fixedAssetFurniture)]),g(96,'Kardex','fa-solid fa-warehouse',[l(97,'Materia prima',R.rawMaterialKardex),l(98,'Productos terminados',R.finishedProductKardex),l(99,'Artículos de reventa',R.resaleItemKardex),l(100,'Todos los productos',R.allProductKardex),l(101,'Stock total RECUMET',R.totalStock),l(102,'Ajuste diferencia stock–Kardex',R.stockDiagnostic),l(103,'Reporte de Kardex',R.kardexReport)]),
t(110,'Administración'),g(111,'Almacén','fa-solid fa-warehouse',[l(112,'Unidades de medida',R.units),l(113,'Balanzas',R.scales),l(114,'Categorías',R.categories),l(115,'Productos',R.products)]),g(116,'Configuración','fa-solid fa-gears',[l(117,'Usuarios',R.users),l(118,'Empresa',R.company),l(119,'Sucursales',R.branches),l(120,'Almacenes',R.storages),l(121,'Compañías de transporte',R.transportCompanies)]),
t(130,'Reportes'),g(131,'Reportes','fa-solid fa-chart-column',[l(132,'Reporte gerencial',R.managementReport),l(133,'Reporte de contabilidad',R.accountingReport)])];
